# Generated by Django 3.2.3 on 2021-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('question1', models.CharField(default='answ1', max_length=20)),
                ('question2', models.CharField(default='answ2', max_length=20)),
                ('question3', models.CharField(default='answ3', max_length=20)),
                ('question4', models.CharField(default='answ4', max_length=20)),
                ('question5', models.CharField(default='answ5', max_length=20)),
                ('question6', models.CharField(default='answ6', max_length=20)),
                ('question7', models.IntegerField(default=0)),
                ('question8', models.CharField(default='answ8', max_length=20)),
                ('question9', models.CharField(default='answ9', max_length=20)),
                ('question10', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(default='xxx@soccernet.pt', max_length=50)),
                ('date_Of_Birth', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=999000999)),
            ],
        ),
        migrations.CreateModel(
            name='User_Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=0)),
                ('opinion_text', models.CharField(max_length=300)),
                ('opinion2', models.IntegerField(default=0)),
                ('opinion3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('quizzes', models.ManyToManyField(blank=True, related_name='QuizzesUser', to='website.Quizz')),
            ],
        ),
    ]
