# Generated by Django 3.2.3 on 2021-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autenticated',
            field=models.BooleanField(default=False),
        ),
    ]
