# Generated by Django 3.2.3 on 2021-06-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_autenticated_user_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='quizzuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_quizz', to='website.user_details'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
