# Generated by Django 3.2.3 on 2021-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210614_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizzUser',
            new_name='Quizz',
        ),
        migrations.CreateModel(
            name='User_Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('quizzes', models.ManyToManyField(blank=True, related_name='QuizzesUser', to='website.Quizz')),
            ],
        ),
    ]
