# Generated by Django 3.2.3 on 2021-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210618_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='date_Of_Birth',
            field=models.CharField(default='18/05/2001', max_length=50),
        ),
    ]
