# Generated by Django 3.2.3 on 2021-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_user_details_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='question1',
            field=models.CharField(default='answ1', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question10',
            field=models.CharField(default='answ10', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question2',
            field=models.CharField(default='answ2', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question3',
            field=models.CharField(default='answ3', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question4',
            field=models.CharField(default='answ4', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question5',
            field=models.CharField(default='answ5', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question6',
            field=models.CharField(default='answ6', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question7',
            field=models.CharField(default='answ7', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question8',
            field=models.CharField(default='answ8', max_length=20),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question9',
            field=models.CharField(default='answ9', max_length=20),
        ),
    ]
