# Generated by Django 3.2.3 on 2021-06-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_quizz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_quizz',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='id_user_quizz', to='website.Quizz'),
        ),
    ]
