# Generated by Django 3.2.3 on 2021-07-02 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_auto_20210626_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='user_id_quizz',
            field=models.ManyToManyField(blank=True, related_name='QuizzesUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_quizz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='date_Of_Birth',
            field=models.CharField(default='dd/mm/yyyy', max_length=50),
        ),
        migrations.DeleteModel(
            name='User_Quizz',
        ),
    ]
