# Generated by Django 3.2.3 on 2021-07-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210702_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_quizz', to='website.user_details'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='user_id_quizz',
            field=models.ManyToManyField(blank=True, related_name='QuizzesUser', to='website.User_details'),
        ),
    ]
