# Generated by Django 3.2.3 on 2021-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210702_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.IntegerField(default=999000999),
        ),
    ]
