# Generated by Django 3.2.3 on 2021-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210702_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_quizz',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_quizz',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
