# Generated by Django 3.2.3 on 2021-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210702_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='question10',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='question7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
